---
- name: Deploy 
  hosts: all

  roles:
  - name: Install certbot
    role: certbot
  - name: Install envoy
    role: envoy
  - name: Install Docker
    role: docker
  - name: Start challenges
    role: challenges
